
# This file is automatically generated, you probably don't want to edit this

dataMBInppairOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "dataMBInppairOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pairs = NULL,
            SWC = 0.5,
            confint = 90,
            desc = FALSE, ...) {

            super$initialize(
                package='mbir',
                name='dataMBInppair',
                requiresData=TRUE,
                ...)

            private$..pairs <- jmvcore::OptionPairs$new(
                "pairs",
                pairs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..SWC <- jmvcore::OptionNumber$new(
                "SWC",
                SWC,
                min=0,
                default=0.5)
            private$..confint <- jmvcore::OptionNumber$new(
                "confint",
                confint,
                min=50,
                max=99.9,
                default=90)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)

            self$.addOption(private$..pairs)
            self$.addOption(private$..SWC)
            self$.addOption(private$..confint)
            self$.addOption(private$..desc)
        }),
    active = list(
        pairs = function() private$..pairs$value,
        SWC = function() private$..SWC$value,
        confint = function() private$..confint$value,
        desc = function() private$..desc$value),
    private = list(
        ..pairs = NA,
        ..SWC = NA,
        ..confint = NA,
        ..desc = NA)
)

dataMBInppairResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        ttest = function() private$.items[["ttest"]],
        effect = function() private$.items[["effect"]],
        mbi = function() private$.items[["mbi"]],
        desc = function() private$.items[["desc"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="MBI for Paired Samples (non-parametric)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="MBI for Wilcoxon signed-rank test"))
            self$add(jmvcore::Table$new(
                options=options,
                name="ttest",
                title="Wilcoxon signed-rank test",
                rows="(pairs)",
                clearWith=list(
                    "confint",
                    "SWC"),
                columns=list(
                    list(
                        `name`="i1", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="i2", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effect",
                title="Effect Size",
                rows="(pairs)",
                clearWith=list(
                    "confint",
                    "SWC"),
                columns=list(
                    list(
                        `name`="i1", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="i2", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="r", 
                        `type`="number", 
                        `title`="Effect Size (r)"),
                    list(
                        `name`="rLL", 
                        `type`="number", 
                        `title`="Lower", 
                        `superTitle`="Confidence Interval"),
                    list(
                        `name`="rUL", 
                        `type`="number", 
                        `title`="Upper", 
                        `superTitle`="Confidence Interval"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mbi",
                title="Magnitude Based Inference",
                rows="(pairs)",
                clearWith=list(
                    "confint",
                    "SWC"),
                columns=list(
                    list(
                        `name`="i1", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="i2", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="negative", 
                        `type`="number", 
                        `title`="Negative", 
                        `superTitle`="MBI (%)"),
                    list(
                        `name`="trivial", 
                        `type`="number", 
                        `title`="Trivial", 
                        `superTitle`="MBI (%)"),
                    list(
                        `name`="positive", 
                        `type`="number", 
                        `title`="Positive", 
                        `superTitle`="MBI (%)"),
                    list(
                        `name`="inference", 
                        `title`="Inference", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Descriptives",
                visible="(desc)",
                rows="(pairs)",
                clearWith=list(
                    "group"),
                columns=list(
                    list(
                        `name`="name[1]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="n[1]", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="m[1]", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="med[1]", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="sd[1]", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="se[1]", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="name[2]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="n[2]", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="m[2]", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="med[2]", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="sd[2]", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="se[2]", 
                        `title`="SE", 
                        `type`="number"))))}))

dataMBInppairBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "dataMBInppairBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'mbir',
                name = 'dataMBInppair',
                version = c(1,0,0),
                options = options,
                results = dataMBInppairResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' MBI for Paired Samples (non-parametric)
#'
#' 
#'
#' @examples
#' \dontrun{
#' 
#' data('bugs', package = 'jmv')
#'
#' mbir::dataMBInppair(
#'   data = bugs,
#'   pairs = list(
#'     list(
#'       i1="LDHF",
#'       i2="LDLF")))
#'
#' #  Wilcoxon signed-rank test
#' #  ---------------------------------------
#' #                    statistic    p
#' #  ---------------------------------------
#' #    LDHF    LDLF         2250    < .001
#' #  ---------------------------------------
#' #
#' #
#'
#' #
#' #  Effect Size
#' #  -------------------------------------------------
#' #                    Effect Size    Lower    Upper
#' #  -------------------------------------------------
#' #    LDHF    LDLF          0.585    0.458    0.689
#' #  -------------------------------------------------
#' #
#' #
#'
#' #
#' #  Magnitude Based Inference
#' #  -----------------------------------------------------------------------------------------
#' #                    Negative    Trivial    Positive    Inference
#' #  -----------------------------------------------------------------------------------------
#' #    LDHF    LDLF        0.00       0.00         100    Almost Certainly Large Effect Size
#' #  -----------------------------------------------------------------------------------------
#' #
#' #
#'}
#' @param data the data as a data frame
#' @param pairs a list of vectors of strings naming variables to pair from
#'   \code{data}
#' @param SWC a number that defines the bounds for magnitude-based inference
#' @param confint 90\% (default), confidence interval for magnitude-based
#'   inference
#' @param desc \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   statistics
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ttest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effect} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mbi} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ttest$asDF}
#'
#' \code{as.data.frame(results$ttest)}
#'
#' @export
dataMBInppair <- function(
    data,
    pairs,
    SWC = 0.5,
    confint = 90,
    desc = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('dataMBInppair requires jmvcore to be installed (restart may be required)')

    options <- dataMBInppairOptions$new(
        pairs = pairs,
        SWC = SWC,
        confint = confint,
        desc = desc)

    results <- dataMBInppairResults$new(
        options = options)

    analysis <- dataMBInppairClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
