
# This file is automatically generated, you probably don't want to edit this

dataMBIcorrOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "dataMBIcorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pairs = NULL,
            pearson = TRUE,
            spear = FALSE,
            kendall = FALSE,
            SWC = 0.1,
            confint = 90,
            desc = FALSE, ...) {

            super$initialize(
                package='mbir',
                name='dataMBIcorr',
                requiresData=TRUE,
                ...)

            private$..pairs <- jmvcore::OptionPairs$new(
                "pairs",
                pairs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..pearson <- jmvcore::OptionBool$new(
                "pearson",
                pearson,
                default=TRUE)
            private$..spear <- jmvcore::OptionBool$new(
                "spear",
                spear,
                default=FALSE)
            private$..kendall <- jmvcore::OptionBool$new(
                "kendall",
                kendall,
                default=FALSE)
            private$..SWC <- jmvcore::OptionNumber$new(
                "SWC",
                SWC,
                min=0.01,
                max=0.9,
                default=0.1)
            private$..confint <- jmvcore::OptionNumber$new(
                "confint",
                confint,
                min=50,
                max=99.9,
                default=90)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)

            self$.addOption(private$..pairs)
            self$.addOption(private$..pearson)
            self$.addOption(private$..spear)
            self$.addOption(private$..kendall)
            self$.addOption(private$..SWC)
            self$.addOption(private$..confint)
            self$.addOption(private$..desc)
        }),
    active = list(
        pairs = function() private$..pairs$value,
        pearson = function() private$..pearson$value,
        spear = function() private$..spear$value,
        kendall = function() private$..kendall$value,
        SWC = function() private$..SWC$value,
        confint = function() private$..confint$value,
        desc = function() private$..desc$value),
    private = list(
        ..pairs = NA,
        ..pearson = NA,
        ..spear = NA,
        ..kendall = NA,
        ..SWC = NA,
        ..confint = NA,
        ..desc = NA)
)

dataMBIcorrResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        mbi = function() private$.items[["mbi"]],
        desc = function() private$.items[["desc"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="MBI for Correlation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="MBI for Correlation"))
            self$add(jmvcore::Table$new(
                options=options,
                name="mbi",
                title="Magnitude Based Inference: Correlation",
                rows="(pairs)",
                clearWith=list(
                    "confint",
                    "SWC"),
                columns=list(
                    list(
                        `name`="i1", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="i2", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="b[0]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Pearson's r", 
                        `visible`="(pearson)"),
                    list(
                        `name`="correl[0]", 
                        `title`="", 
                        `type`="Number", 
                        `visible`="(pearson)"),
                    list(
                        `name`="p[0]", 
                        `title`="p", 
                        `type`="Number", 
                        `format`="zto,pvalue", 
                        `visible`="(pearson)"),
                    list(
                        `name`="Negative[0]", 
                        `type`="Number", 
                        `title`="Negative (%)", 
                        `visible`="(pearson)"),
                    list(
                        `name`="Trivial[0]", 
                        `type`="Number", 
                        `title`="Trivial (%)", 
                        `visible`="(pearson)"),
                    list(
                        `name`="Positive[0]", 
                        `type`="Number", 
                        `title`="Positive (%)", 
                        `visible`="(pearson)"),
                    list(
                        `name`="Inference[0]", 
                        `title`="Inference", 
                        `type`="text", 
                        `visible`="(pearson)"),
                    list(
                        `name`="b[1]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Spearman's rho", 
                        `visible`="(spear)"),
                    list(
                        `name`="correl[1]", 
                        `title`="", 
                        `type`="Number", 
                        `visible`="(spear)"),
                    list(
                        `name`="p[1]", 
                        `title`="p", 
                        `type`="Number", 
                        `format`="zto,pvalue", 
                        `visible`="(spear)"),
                    list(
                        `name`="Negative[1]", 
                        `type`="Number", 
                        `title`="Negative (%)", 
                        `visible`="(spear)"),
                    list(
                        `name`="Trivial[1]", 
                        `type`="Number", 
                        `title`="Trivial (%)", 
                        `visible`="(spear)"),
                    list(
                        `name`="Positive[1]", 
                        `type`="Number", 
                        `title`="Positive (%)", 
                        `visible`="(spear)"),
                    list(
                        `name`="Inference[1]", 
                        `title`="Inference", 
                        `type`="text", 
                        `visible`="(spear)"),
                    list(
                        `name`="b[2]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Kendall's tau-b", 
                        `visible`="(kendall)"),
                    list(
                        `name`="correl[2]", 
                        `title`="", 
                        `type`="Number", 
                        `visible`="(kendall)"),
                    list(
                        `name`="p[2]", 
                        `title`="p", 
                        `type`="Number", 
                        `format`="zto,pvalue", 
                        `visible`="(kendall)"),
                    list(
                        `name`="Negative[2]", 
                        `type`="Number", 
                        `title`="Negative (%)", 
                        `visible`="(kendall)"),
                    list(
                        `name`="Trivial[2]", 
                        `type`="Number", 
                        `title`="Trivial (%)", 
                        `visible`="(kendall)"),
                    list(
                        `name`="Positive[2]", 
                        `type`="Number", 
                        `title`="Positive (%)", 
                        `visible`="(kendall)"),
                    list(
                        `name`="Inference[2]", 
                        `title`="Inference", 
                        `type`="text", 
                        `visible`="(kendall)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Descriptives",
                visible="(desc)",
                rows="(pairs)",
                clearWith=list(
                    "group"),
                columns=list(
                    list(
                        `name`="name[1]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="n[1]", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="m[1]", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="med[1]", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="sd[1]", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="se[1]", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="name[2]", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="n[2]", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="m[2]", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="med[2]", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="sd[2]", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="se[2]", 
                        `title`="SE", 
                        `type`="number"))))}))

dataMBIcorrBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "dataMBIcorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'mbir',
                name = 'dataMBIcorr',
                version = c(1,0,0),
                options = options,
                results = dataMBIcorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' MBI for Correlation
#'
#' 
#'
#' @examples
#' \dontrun{
#' 
#' data('bugs', package = 'jmv')
#'
#' mbir::dataMBIcorr(
#'     data = data,
#'     pairs = list(
#'         list(
#'             i1="LDLF",
#'             i2="LDHF")))
#'
#' #
#' #  Magnitude Based Inference: Correlation
#' #  -------------------------------------------------------------------------------------------------------------------------------------------------
#' #                                            p         Negative (\%)    Trivial (\%)    Positive (\%)    Inference
#' #  -------------------------------------------------------------------------------------------------------------------------------------------------
#' #    LDLF    LDHF    Pearson's r    0.577    < .001            0.00           0.00             100    Almost Certainly Large Positive Correlation.
#' #  -------------------------------------------------------------------------------------------------------------------------------------------------
#' #
#' #
#'}
#' @param data the data as a data frame
#' @param pairs a list of vectors of strings naming variables to pair from
#'   \code{data}
#' @param pearson \code{TRUE} (default) or \code{FALSE}, provide Pearson's R
#' @param spear \code{TRUE} or \code{FALSE} (default), provide Spearman's rho
#' @param kendall \code{TRUE} or \code{FALSE} (default), provide Kendall's
#'   tau-b
#' @param SWC a number, default (r=0.1) that defines the bounds for
#'   magnitude-based inference
#' @param confint 90\% (default), confidence interval for magnitude-based
#'   inference
#' @param desc \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   statistics
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$mbi} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$mbi$asDF}
#'
#' \code{as.data.frame(results$mbi)}
#'
#' @export
dataMBIcorr <- function(
    data,
    pairs,
    pearson = TRUE,
    spear = FALSE,
    kendall = FALSE,
    SWC = 0.1,
    confint = 90,
    desc = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('dataMBIcorr requires jmvcore to be installed (restart may be required)')

    options <- dataMBIcorrOptions$new(
        pairs = pairs,
        pearson = pearson,
        spear = spear,
        kendall = kendall,
        SWC = SWC,
        confint = confint,
        desc = desc)

    results <- dataMBIcorrResults$new(
        options = options)

    analysis <- dataMBIcorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
